# Generated by Django 4.0.3 on 2022-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='PortfolioApp/uploads'),
        ),
        migrations.AlterField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
