# Generated by Django 4.0.3 on 2022-07-08 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name': 'ProjectImage', 'verbose_name_plural': 'Project Images'},
        ),
    ]
