# Generated by Django 4.0.3 on 2022-06-08 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='created',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='updated',
        ),
    ]
